version: 2
jobs:
  build:

    environment:
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f Dockerfile.client .
      - run: docker build -f Dockerfile.server .

