version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f Dockerfile.client .
      - run: docker build -f Dockerfile.server .

