version: 2.1
jobs:
  build-client:
    machine: true
    steps:
      - checkout
      - run: docker build -f Dockerfile.client .
  build-server:
    machine: true
    steps:
      - checkout
      - run: docker build -f Dockerfile.server .
workflows:
  version: 2
  my_flow:
    jobs:
      - build-client
      - build-server
  my_flow2:
    jobs:
      - build-server
      - build-client:
          requires:
            - build-server
        
