version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f Dockerfile.client .
      - run: docker build -f Dockerfile.server .

