version: 2.1

commands:

  build-docker-image:
    parameters:
      file:
        type: string
        default: Dockerfile
    steps:
      - run: docker build -f << parameters.file >> .

  cancel_job:
    steps:
      - run:
          name: Cancel current job 
          environment:
            CURL: "curl -s -u ${CIRCLE_TOKEN}: -H 'Accept: application/json'"
          command: |
            ${CURL}         https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job | jq -r \".items[] | select(.id == \\\"${CIRCLE_WORKFLOW_JOB_ID}\\\") | .job_number\" | tee .job_number
            ${CURL} -X POST https://circleci.com/api/v2/project/github/aadamovich/knock-knock-docker/job/$(cat .job_number)/cancel

  cancel_workflow:
    steps:
      - run:
          name: Cancel current workflow 
          environment:
            CURL: "curl -s -u ${CIRCLE_TOKEN}: -H 'Accept: application/json'"
          command: | 
            ${CURL} -X POST https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel

jobs:
  build-client:
    machine: true
    steps:
      - checkout
      - build-docker-image: { file: "Dockerfile.client" }
  cancel-flow:
    machine: true
    steps:
      - checkout
      - cancel_workflow
  cancel-client:
    machine: true
    steps:
      - checkout
      - cancel_job
      - build-docker-image: { file: "Dockerfile.client" }
  build-server:
    machine: true
    steps:
      - checkout
      - build-docker-image:
          file: Dockerfile.server
  deploy-to-prod:
    machine: true
    steps:
      - checkout
      - run: echo Yes
  debug:
    machine: true
    steps:
      - checkout
      - run: echo debug


workflows:
  version: 2
  my_flow:
    jobs:
      - cancel-client
      - build-server
  my_flow2:
    jobs:
      - build-server
      - build-client:
          requires:
            - build-server
  my_flow3:
    jobs:
      - build-client
      - approve-deployment:
          type: approval
          requires:
            - build-client
      - deploy-to-prod:
          requires:
            - approve-deployment
  my_flow4:
    jobs:
      - cancel-flow

