version: 2.1

commands:

  build-docker-image:
    parameters:
      file:
        type: string
        default: Dockerfile
    steps:
      - run: docker build -f << parameters.file >> .

  cancel_job:
    steps:
      - run:
          name: Get current job number 
          command: |
            curl -s -u ${CIRCLE_TOKEN}: -H 'Accept: application/json' -X GET https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job | jq -r ".items[] | select(.id == \"${CIRCLE_WORKFLOW_JOB_ID}\") | .job_number" | tee .job_number
      - run:
          name: Cancel job 
          command: | 
            curl -s -u ${CIRCLE_TOKEN}: -H 'Accept: application/json' -X POST https://circleci.com/api/v2/project/github/aadamovich/knock-knock-docker/job/$(cat .job_number)/cancel
#          command: |
#            ${CURL} ${API}/workflow/${CIRCLE_WORKFLOW_ID}/job | tee .jobs.json
#            cat .jobs.json | jq -r ".items[] | select(.id == \"${CIRCLE_WORKFLOW_JOB_ID}\") | .job_number" | tee .job_number
#            ${CURL} -X POST ${API}/project/github/aadamovich/knock-knock-docker/job/$(cat .job_number)/cancel

  cancel_workflow:
    steps:
      - run:
          name: Cancel current workflow 
          environment:
            API: "https://circleci.com/api/v2"
            CURL: "curl -s -u ${CIRCLE_TOKEN}: -H 'Accept: application/json'"
          command: |
            ${CURL} -X POST ${API}/workflow/${CIRCLE_WORKFLOW_ID}/cancel
            sleep 20

jobs:
  build-client:
    machine: true
    steps:
      - checkout
      - build-docker-image: { file: "Dockerfile.client" }
  cancel-flow:
    machine: true
    steps:
      - checkout
      - cancel_workflow
  cancel-client:
    machine: true
    steps:
      - checkout
      - cancel_job
      - build-docker-image: { file: "Dockerfile.client" }
  build-server:
    machine: true
    steps:
      - checkout
      - build-docker-image:
          file: Dockerfile.server
  deploy-to-prod:
    machine: true
    steps:
      - checkout
      - run: echo Yes
  debug:
    machine: true
    steps:
      - checkout
      - run: echo debug


workflows:
  version: 2

#   parallel_jobs_one_cancelled:
#     jobs:
#       - build-client
#       - cancel-client
#       - build-server:
#           requires:
#             - build-client

  sequential_jobs_first_cancelled:
    jobs:
      - cancel-client
      - build-server:
          requires:
            - cancel-client

#   sequential_jobs_last_cancelled:
#     jobs:
#       - build-server
#       - cancel-client:
#           requires:
#             - build-server

#   sequential_jobs:
#     jobs:
#       - build-server
#       - build-client:
#           requires:
#             - build-server

#   sequential_jobs_with_approval:
#     jobs:
#       - build-client
#       - approve-deployment:
#           type: approval
#           requires:
#             - build-client
#       - deploy-to-prod:
#           requires:
#             - approve-deployment

  cancel_flow:
    jobs:
      - cancel-flow

