version: 2.1

commands:
  build-docker-image:
    parameters:
      file:
        type: string
        default: Dockerfile
    steps:
      - run: docker build -f << parameters.file >> .


jobs:
  build-client:
    machine: true
    steps:
      - checkout
      - build-docker-image: { file: "Dockerfile.client" }
  build-server:
    machine: true
    steps:
      - checkout
      - build-docker-image:
          file: Dockerfile.server
  deploy-to-prod:
    machine: true
    steps:
      - checkout
      - run: echo Yes


workflows:
  version: 2
  my_flow:
    jobs:
      - build-client
      - build-server
  my_flow2:
    jobs:
      - build-server
      - build-client:
          requires:
            - build-server
  my_flow3:
    jobs:
      - build-client
      - build-server
      - approve-deployment:
          type: approval
          requires:
            - build-server
            - build-client
      - deploy-to-prod:
          requires:
            - build-server
            - build-client
            - approve-deployment
